default: &default
  adapter: postgresql
  username: deploy
  password: 12345
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: saintlbeau-development

test:
  <<: *default
  database: saintlbeau-test

production:
  <<: *default
  database: saintlbeau-production

staging:
  <<: *default
  database: saintlbeau-staging
