default: &default
  adapter: postgresql
  username: postgres
  password: 12345
  pool: 15
  timeout: 5000

development:
  <<: *default
  database: ynbclub

test:
  <<: *default
  database: ynbclub

production:
  <<: *default
  database: ynbclub
