default: &default
  adapter: postgresql
  username: 
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: saintLBeau-app

test:
  <<: *default
  database: saintLBeau-app

production:
  <<: *default
  database: saintLBeau-app

staging:
  <<: *default
  database: saintlbeau-staging
