development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: saintLBeau-app
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: saintLBeau-app
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: saintLBeau-app
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  database: saintlbeau-staging
  pool: 5
