meta_title: "YnbClub"
meta_description: "Relevant description"
meta_image: "download.jpeg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Card